[tox]
envlist = py{3.10,3.11,3.12,3.13,3.8,3.9}, coverage, style

[testenv]
setenv = COVERAGE_FILE={toxworkdir}/.coverage.{envname}
usedevelop = True
deps = -rrequirements.txt
       -rtests/requirements.txt
commands = pytest {posargs:-s -n auto -vv --junit-xml="{toxworkdir}/junit.{envname}.xml" --cov=src/ tests/}

[testenv:coverage]
setenv = COVERAGE_FILE={toxworkdir}/.coverage
skip_install = True
deps = coverage
commands = coverage combine
           coverage html
           coverage xml
           coverage report -m

[testenv:style]
skip_install = True
deps = flake8
       flake8-import-order
commands = flake8 {posargs:--extend-ignore=E203 src/ tests/ setup.py}

[testenv:security]
skip_install = True
deps = bandit
commands = bandit {posargs:-r src/}

[testenv:black]
skip_install = True
deps = black
commands = black {posargs:-l140 src/ tests/ setup.py}


[coverage:xml]
output = .tox/test-reports/coverage.xml
[coverage:html]
directory = .tox/test-reports/htmlcov
[coverage:run]
omit = src/core/features/filterbank.py
[coverage:report]
show_missing = true
skip_empty = true

[pytest]
cache_dir = .tox/.cache

[flake8]
max-line-length = 140
max-complexity = 20
show-source = True
# See https://github.com/PyCQA/flake8-import-order
import-order-style = edited
application-import-names = seabass
