# Manuals metadata file.
metadataVersion: 2

# Identifiers for this documentation bundle
name: seabass

# Email distro for doc maintainers
owner: kwatcharasupat@ieee.org

# Display name and description
displayName: Seabass
description: Python implementation of 2f-model and some PEAQ MOVs

# Relative path to an image located in either the .manuals metadata directory or site root directory.
coverImagePath:

# Grouping will help users discover your docs by clustering them
# in hierarchical trees. One such tree could be org -> repo -> name,
# but you are free to choose whatever levels make sense for your docs
groupingLevel1:
groupingLevel2:
groupingLevel3:

# Comma separated tags for discovery (not implemented yet)
tags:

# Git clone URL of the repo whose code is being documented by this manual page.
# Sometimes this is the same as the manual repo (when the manual is stored in the same repo as the code)
# and sometimes it is its own repository.
codeRepoPath: 

# Valid options are:
# draft - The manual is incomplete and not ready to be published.
# published - The docs are complete and up-to-date.
# deprecated - The content has sufficiently changed so as to render this documentation irrelevant, and it is being kept for posterity only.
# superseded - A new manual with sufficiently different information such that this manual exists for historical purposes only. In this state, the old documentation should redirect to the new version.
docLifecycleStatus: "published"